### ISSUE TITLE
Implement env_file, cap and add_host

### ISSUE THREAD

**Issue by tcoats** [metocean/tugboat#10]
https://github.com/docker/fig/releases/tag/1.1.0-rc1

**Comment by tcoats** [comment]
Let's get our .yml format up to scratch with docker compose.
https://github.com/docker/compose/releases/

At least env_file, cap and add_host are needed.

**Comment by ajnisbet** [comment]
So now what's missing from tugboat is: external_links, volumes_from, dns_search, stdin_open, tty, cpu_shares. Do we want any of those implemented?

**Comment by tcoats** [comment]
stdin_open and tty are more interactive and are part of ducke instead. The idea is that tugboat is for daemonising, and ducke for testing and lower level queries. This can of course change, it's just the initial direction.

external_links, dns_search and cpu_shares can go on the backlog and aren't needed immediately.
fig, and I think docker-compose, uses volumes_from as part of it's migration. Perhaps there is a need for it? I don't really know the use case.
