### ISSUE TITLE
Remove Logs on tug up

### ISSUE THREAD

**Issue by Tornado-Tim** [metocean/tugboat#17]
When the tug up command is issued, logs get appended at the end.
This can mislead a person that the tug up command hasnt finished, and will continue to wait.

I would recommend going back to the previous behaviour, as the logs can be launched by going to tug logs instead.

Consideration may need to be taken as a person may not want the logs to be kept open, perhaps add another parameter to the logs with an i for a logs interactive session where it keeps it open otherwise it get the latest log entries but then stop.

Reason why I think this important is when webservices go live and logging is enabled, the person viewing the log wont have enough time to view all the stuff on the screen as the log will be constantly written to when traffic goes to it.

**Comment by tcoats** [comment]
Done.
